# DATA PREPROCESSING TOOLS 

In [45]:
# Libraries 

import numpy as np 
import matplotlib as plt
import pandas as pd

In [4]:
dataset = pd.read_csv('Product.csv')
dataset

,Country,Age,Salary,Purchased
0,France,44.0,72000.0,No
1,Spain,27.0,48000.0,Yes
2,Germany,30.0,54000.0,No
3,Spain,38.0,61000.0,No
4,Germany,40.0,NaN,Yes
5,France,35.0,58000.0,Yes
6,Spain,NaN,52000.0,No
7,France,48.0,79000.0,Yes
8,Germany,50.0,83000.0,No
9,France,37.0,67000.0,Yes


In [5]:
# numpy 

x_raw = dataset.iloc[:, :-1].values
y_raw = dataset.iloc[:, -1].values

In [6]:
# pandas
dfx_raw = dataset.iloc[:, :-1]
seriesy_rawdfx =  dataset.iloc[:, -1]

In [7]:
# copy the data to another varible 

dfx = dfx_raw.copy()
seriesy = seriesy_rawdfx.copy()
x = x_raw.copy()
y =y_raw.copy()

In [8]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [9]:
print(type(x))
print(type(dfx))

<class 'numpy.ndarray'>
<class 'pandas.core.frame.DataFrame'>


# Handling the missing values 

In [10]:
print(dfx.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Country  10 non-null     object 
 1   Age      9 non-null      float64
 2   Salary   9 non-null      float64
dtypes: float64(2), object(1)
memory usage: 368.0+ bytes
None


In [11]:
# Info will not work with numpy array 
print(x.info()) 

AttributeError: 'numpy.ndarray' object has no attribute 'info'

In [12]:
# Change numpy array to dataframe 
x = pd.DataFrame(x)
x.info

<bound method DataFrame.info of          0     1        2
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0>

In [13]:
# Then change to numpy

x = x.values
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [14]:
print(dfx.isnull().sum())

Country    0
Age        1
Salary     1
dtype: int64


In [15]:
# isnull will not work for numpy array
print(x.isnull().sum())

AttributeError: 'numpy.ndarray' object has no attribute 'isnull'

In [16]:
dfx_raw

,Country,Age,Salary
0,France,44.0,72000.0
1,Spain,27.0,48000.0
2,Germany,30.0,54000.0
3,Spain,38.0,61000.0
4,Germany,40.0,NaN
5,France,35.0,58000.0
6,Spain,NaN,52000.0
7,France,48.0,79000.0
8,Germany,50.0,83000.0
9,France,37.0,67000.0


In [17]:
dfx

,Country,Age,Salary
0,France,44.0,72000.0
1,Spain,27.0,48000.0
2,Germany,30.0,54000.0
3,Spain,38.0,61000.0
4,Germany,40.0,NaN
5,France,35.0,58000.0
6,Spain,NaN,52000.0
7,France,48.0,79000.0
8,Germany,50.0,83000.0
9,France,37.0,67000.0


In [18]:
dfx = dfx.fillna(0)
dfx

,Country,Age,Salary
0,France,44.0,72000.0
1,Spain,27.0,48000.0
2,Germany,30.0,54000.0
3,Spain,38.0,61000.0
4,Germany,40.0,0.0
5,France,35.0,58000.0
6,Spain,0.0,52000.0
7,France,48.0,79000.0
8,Germany,50.0,83000.0
9,France,37.0,67000.0


In [19]:
# replace all zeroes with nan values 
dfx = dfx.replace(0, np.nan)
dfx

,Country,Age,Salary
0,France,44.0,72000.0
1,Spain,27.0,48000.0
2,Germany,30.0,54000.0
3,Spain,38.0,61000.0
4,Germany,40.0,NaN
5,France,35.0,58000.0
6,Spain,NaN,52000.0
7,France,48.0,79000.0
8,Germany,50.0,83000.0
9,France,37.0,67000.0


In [20]:
index_no = dfx.columns.get_loc('Age')
index_no

1

In [21]:
dfx.iloc[:,1] = dfx.iloc[:,1].fillna(5)
dfx

,Country,Age,Salary
0,France,44.0,72000.0
1,Spain,27.0,48000.0
2,Germany,30.0,54000.0
3,Spain,38.0,61000.0
4,Germany,40.0,NaN
5,France,35.0,58000.0
6,Spain,5.0,52000.0
7,France,48.0,79000.0
8,Germany,50.0,83000.0
9,France,37.0,67000.0


In [22]:
# Getting the old data 
dfx = dfx_raw.copy()
dfx

,Country,Age,Salary
0,France,44.0,72000.0
1,Spain,27.0,48000.0
2,Germany,30.0,54000.0
3,Spain,38.0,61000.0
4,Germany,40.0,NaN
5,France,35.0,58000.0
6,Spain,NaN,52000.0
7,France,48.0,79000.0
8,Germany,50.0,83000.0
9,France,37.0,67000.0


In [23]:
# Missing values imputation on dataframe

# Replace with mean values

In [24]:
dfx_raw

,Country,Age,Salary
0,France,44.0,72000.0
1,Spain,27.0,48000.0
2,Germany,30.0,54000.0
3,Spain,38.0,61000.0
4,Germany,40.0,NaN
5,France,35.0,58000.0
6,Spain,NaN,52000.0
7,France,48.0,79000.0
8,Germany,50.0,83000.0
9,France,37.0,67000.0


In [25]:
# dataframe
dfx = dfx_raw.copy()
from sklearn.impute import SimpleImputer # Simple imputer is the class that is used to handle the missing values with simple startigies
imputer = SimpleImputer(missing_values = np.nan, strategy ='mean')

#imputer.fit(dfx.iloc[:,1:3])
#dfx.iloc[:, 1:3] = imputer.transform(dfx.iloc[:, 1:3])
#dfx.iloc[:, 1:3] = imputer.fit(dfx.iloc[:, 1:3]).transform(dfx.iloc[:, 1:3])

dfx.iloc[:, 1:3] = imputer.fit_transform(dfx.iloc[:, 1:3])
dfx

,Country,Age,Salary
0,France,44.000000,72000.000000
1,Spain,27.000000,48000.000000
2,Germany,30.000000,54000.000000
3,Spain,38.000000,61000.000000
4,Germany,40.000000,63777.777778
5,France,35.000000,58000.000000
6,Spain,38.777778,52000.000000
7,France,48.000000,79000.000000
8,Germany,50.000000,83000.000000
9,France,37.000000,67000.000000


In [26]:
# Strategy
#Mean
#Median

In [27]:
#
dfx = dfx_raw.copy()
dfx

,Country,Age,Salary
0,France,44.0,72000.0
1,Spain,27.0,48000.0
2,Germany,30.0,54000.0
3,Spain,38.0,61000.0
4,Germany,40.0,NaN
5,France,35.0,58000.0
6,Spain,NaN,52000.0
7,France,48.0,79000.0
8,Germany,50.0,83000.0
9,France,37.0,67000.0


In [28]:
#Replace with constant values

In [29]:
#dataframe
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy='constant', fill_value=5)
imputer.fit(dfx.iloc[:, 1:3])
dfx.iloc[:, 1:3] = imputer.fit(dfx.iloc[:, 1:3]).transform(dfx.iloc[:, 1:3])
dfx

,Country,Age,Salary
0,France,44.0,72000.0
1,Spain,27.0,48000.0
2,Germany,30.0,54000.0
3,Spain,38.0,61000.0
4,Germany,40.0,5.0
5,France,35.0,58000.0
6,Spain,5.0,52000.0
7,France,48.0,79000.0
8,Germany,50.0,83000.0
9,France,37.0,67000.0


In [30]:
# Replace  with mean values

In [31]:
x_raw

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [32]:
x=x_raw.copy()
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [33]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [34]:
# Encoding the categorical data

In [35]:
# Encoding the independent data

In [36]:
# pandas
dfx = pd.get_dummies(dfx, columns=['Country']) #one-hot encoding (for each categorical data)
dfx

,Age,Salary,Country_France,Country_Germany,Country_Spain
0,44.0,72000.0,1,0,0
1,27.0,48000.0,0,0,1
2,30.0,54000.0,0,1,0
3,38.0,61000.0,0,0,1
4,40.0,5.0,0,1,0
5,35.0,58000.0,1,0,0
6,5.0,52000.0,0,0,1
7,48.0,79000.0,1,0,0
8,50.0,83000.0,0,1,0
9,37.0,67000.0,1,0,0


In [37]:
#get the raw data 
dfx = dfx_raw.copy()
seriesy = seriesy_rawdfx.copy()
x= x_raw.copy()
y = y_raw.copy()

In [49]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder 
#ct = ColumnTransformer(transformers=[('encoder','drop' [0])], remainder= 'passthrough )
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
#ct = ColumnTransformers=[('encoder', OneHotEncoder(), [0])])
x = np.array(ct.fit_transform(x))

In [50]:
print(x)

[[0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 1.0 0.0 40.0 nan]
 [0.0 1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 1.0 nan 52000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


In [51]:
#Encoding the Dependent variable 

In [52]:
# LabelEncoder used to convert the categeorical target level into numerical level 
from sklearn.preprocessing import LabelEncoder  
le = LabelEncoder()
y = le.fit_transform(y)

In [42]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [46]:
le.fit(["india","paris","paris","tokyo","amsterdam"])
print(le.transform(["india","amsterdam","tokyo","paris"]))

[1 0 3 2]


In [47]:
# Splitting the dataset into the training set and Test set

In [58]:
# sample is reproducibility ( can reproduced again )
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [59]:
print(x_train)

[[1.0 0.0 0.0 1.0 nan 52000.0]
 [1.0 0.0 1.0 0.0 40.0 nan]
 [0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 35.0 58000.0]]


In [60]:
print(x_test)

[[1.0 0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


In [61]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [62]:
print(y_test)

[0 1]


In [63]:
# Features Scaling 

In [67]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [68]:
print(x_train)

[[1.0 0.0 0.0 1.2909944487358056 nan -1.0182239953527132]
 [1.0 0.0 1.0 -0.7745966692414834 -0.038910211282047996 nan]
 [0.0 1.0 0.0 -0.7745966692414834 0.5058327466666259 0.583476671494251]
 [1.0 0.0 0.0 1.2909944487358056 -0.3112816902563849 -0.2974586952715793]
 [1.0 0.0 0.0 1.2909944487358056 -1.809324824615238 -1.3385641287221062]
 [0.0 1.0 0.0 -0.7745966692414834 1.0505757046152997 1.1440719048906884]
 [1.0 0.0 1.0 -0.7745966692414834 1.3229471835896367 1.4644120382600814]
 [0.0 1.0 0.0 -0.7745966692414834 -0.7198389087178904 -0.537713795298624]]


In [69]:
print(x_test)

[[1.0 0.0 1.0 -0.7745966692414834 -1.4007676061537326 -0.8580539286680168]
 [0.0 1.0 0.0 -0.7745966692414834 -0.4474674297435534 0.18305150478250995]]
