# KNN Regression

In [17]:
#Importing the necessary libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 
import math

In [18]:
#Importing the data
data = pd.read_csv(r"KNN Regression.csv")
data

,Hight,Weight,Target
0,150,50,1.5
1,155,55,1.2
2,160,60,1.8
3,161,59,2.1
4,158,65,1.7


In [19]:
#Defining Euclidean distance functions
def euclidean_distance(p1,p2):
    return math.sqrt(sum((a - b) ** 2 for a,b in zip(p1,p2)))

In [20]:
#Define KNN Regression function
def knn_classify(train_data, test_point, k):
    distances = []
    for i in range(len(train_data)):
        dist = euclidean_distance(test_point, train_data[i])
        distances.append((dist, y_train[i]))
    print("Distances: \n",distances)
    
    #Sort distances in non decreasing order
    distances.sort(key = lambda x: x[0])
    k_nearest = [label for (_, label) in distances[: k]]
    
    #Mean Value
    y_hat = (sum(k_nearest))/k
    return y_hat

In [21]:
#Segregating data into X and y
train_data = data.iloc[:, :-1].values
y_train = data.iloc[:, -1].values
print(train_data)
print(y_train)

[[150  50]
 [155  55]
 [160  60]
 [161  59]
 [158  65]]
[1.5 1.2 1.8 2.1 1.7]


In [22]:
#Example test point
test_point = [157, 54]

In [23]:
#Predecting the label for k = 1
k = 1
predicted_label = knn_classify(train_data, test_point, k)
print("\nPredicted Target: ", predicted_label)

Distances: 
 [(8.06225774829855, np.float64(1.5)), (2.23606797749979, np.float64(1.2)), (6.708203932499369, np.float64(1.8)), (6.4031242374328485, np.float64(2.1)), (11.045361017187261, np.float64(1.7))]

Predicted Target:  1.2


In [24]:
#Predecting the label for k = 2
k = 2
predicted_label = knn_classify(train_data, test_point, k)
print("\nPredicted Target: ", predicted_label)

Distances: 
 [(8.06225774829855, np.float64(1.5)), (2.23606797749979, np.float64(1.2)), (6.708203932499369, np.float64(1.8)), (6.4031242374328485, np.float64(2.1)), (11.045361017187261, np.float64(1.7))]

Predicted Target:  1.65


In [25]:
#Predecting the label for k = 3
k = 3
predicted_label = knn_classify(train_data, test_point, k)
print("\nPredicted Target: ", predicted_label)

Distances: 
 [(8.06225774829855, np.float64(1.5)), (2.23606797749979, np.float64(1.2)), (6.708203932499369, np.float64(1.8)), (6.4031242374328485, np.float64(2.1)), (11.045361017187261, np.float64(1.7))]

Predicted Target:  1.7


In [26]:
# All values
print("Train Data: ")
print(train_data,"\n")
print("Test Point: ",test_point)

Train Data: 
[[150  50]
 [155  55]
 [160  60]
 [161  59]
 [158  65]] 

Test Point:  [157, 54]
